Ej/maps list
digidem/mapeo-webmaps pull request #81
Opened 2023-02-27 16:55 UTC by lightlii

https://github.com/digidem/mapeo-webmaps/issues/56

A couple of things to note:
- I had some issues with the rebase so I don't seem to have all the latest changes from develop in here, perhaps @ErikSin we can look into that together before  you review this properly
- Slight deviation from the requirements in #56 - Can't sort 'By latest modified' since we don't record that info, (as far as I can tell firebase doesn't record any additional metadata either but I might be wrong).
-  The issue mentions that @ErikSin was going to look into the preview for the thumbnail. I had a look through Mapbox's documentation but didn't see any way we can get a preview of a style from the mapbox API. It looks like the only way would be to use the [static map endpoint](https://docs.mapbox.com/api/maps/static-images/) but that might be overkill for our case, what do you think?

2023-02-27 22:56 UTC, ErikSin requested changes
Looks pretty good. I'm a little confused as when the sort is actually happening. Am I correct that it is not happening right now?

2023-02-27 22:56 UTC, ErikSin commented on src/views/Home/index.tsx
> +  const maps = mapsCollection?.docs.map((map) => ({ ...map?.data(), id: map?.id }))
memoize

2023-02-27 22:56 UTC, ErikSin commented on src/views/Home/index.tsx
> +                <MapsList maps={maps} progress={{ id: 1, loading: uploading }} />
Where is the sorting happening on the map list?

2023-02-27 22:56 UTC, ErikSin commented on src/components/Header/index.tsx
> +          {onClickAddMap ? (
When is there no `onClickAddMap`?

2023-02-27 22:56 UTC, ErikSin commented on src/views/Home/index.tsx
> +          <Uploading progress={progress} />
'`Current File` is not being updated: 
<img width="224" alt="image" src="https://user-images.githubusercontent.com/67773827/221679766-050eade9-8197-4809-a940-fc1db178a967.png">

2023-02-27 22:56 UTC, ErikSin commented on src/hooks/useCreateMap.ts
>  import * as md5 from 'js-md5'
I think the simplest solution here is to just copy and paste `useCreateMap.ts` from `develop`, assuming you didn't touch this file for this PR

2023-02-27 22:56 UTC, ErikSin commented on src/components/MapItem/index.tsx
> +  Tooltip,
Remove `IconButton` and `ToolTip`

2023-02-27 22:56 UTC, ErikSin commented on src/components/MapItem/index.tsx
> +import { collection, FieldValue, Timestamp } from 'firebase/firestore'
Remove `FieldValue`

2023-02-27 22:56 UTC, ErikSin commented on src/components/MapItem/index.tsx
> +  const shareUrl = `${SHARE_URL_BASE}/${user?.uid}/maps/${id}`
Is this working for you? I only have one set of data, and it isn't working for that

2023-02-27 22:56 UTC, ErikSin commented on src/components/MapsList/index.tsx
> +import { Grow, Typography } from '@mui/material'
remove line

2023-02-28 14:56 UTC, lightlii commented on src/views/Home/index.tsx
> +                <MapsList maps={maps} progress={{ id: 1, loading: uploading }} />
the sorting is happening in the query, see the end of line 29 `query(mapsRef, orderBy(sort, 'desc')`

2023-03-01 12:47 UTC, lightlii commented
All fixes done from comments here and I've moved most of the maps list logic (inc NoMaps view) into MapsList as we discussed yesterday. Ready to merge unless you see anything else :)

2023-03-01 16:17 UTC, lightlii commented
Just remembered we said we'd move the sorting to happen locally to reduce queries, so this branch will get an extra commit...

2023-03-02 03:13 UTC, ErikSin commented on src/components/MapsList/index.tsx
> +  ]) as DocumentData[]
This is how you could sortDirectly in TS

````ts
const [mapsCollection = { docs: [] }, mapsLoading] = useCollection(query(mapsRef)) // you can still add an inital sort here, but not necesarry
  const sortedMaps:DocumentData[] = useMemo(() => 
  {
    const unsorted:DocumentData[] = mapsCollection?.docs.map((map) => ({ ...map?.data(), id: map?.id }))

    if(sort === 'createdAt'){
      return unsorted.sort((a,b)=> sortDirection === 'asc' ? a.createdAt.toDate().getTime()-b.createdAt.toDate().getTime(): b.createdAt.toDate().getTime()-a.createdAt.toDate().getTime())
    }

    return unsorted.sort((a,b) => sortDirection === 'asc' ? a.title.localeCompare(b.title) : -1*a.title.localeCompare(b.title))
  }
  , [mapsCollection, sort, sortDirection])
  ```

2023-03-02 03:16 UTC, ErikSin commented on src/components/MapsList/index.tsx
> +// }
can remove

2023-03-02 03:18 UTC, ErikSin approved these changes
just a couple comments to resolve but can be merged

2023-03-02 12:46 UTC, lightlii commented
Added the client-side sorting, can you have a quick look over it before I merge pls @ErikSin ? :)

2023-03-02 16:00 UTC, ErikSin approved these changes
Looks good!

2023-03-02 16:00 UTC, merged